// <auto-generated />
using System;
using System.Collections.Generic;
using HattieAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HattieAI.Infrastructure.Migrations
{
    [DbContext(typeof(HattieDbContext))]
    [Migration("20260611183126_AddIsAiPausedToChatSession")]
    partial class AddIsAiPausedToChatSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HattieAI.Domain.Entities.ApiIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthHeaderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CallCountResetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyCallCount")
                        .HasColumnType("integer");

                    b.Property<int>("DailyCallLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParameterSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestBodyTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApiIntegrations");
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@hattie.ai",
                            PasswordHash = "qRib0c+6Qgc6j+1FmRRHs6VyXhdElC5W4eY3EpP3TLkw3Du/",
                            Role = "Admin",
                            TenantId = "",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAiPaused")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float[]>("Embedding")
                        .HasColumnType("real[]");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId1");

                    b.ToTable("KnowledgeChunks");
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Code");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Code = "zh-CN",
                            Name = "Mandarin Chinese"
                        },
                        new
                        {
                            Code = "hi",
                            Name = "Hindi"
                        },
                        new
                        {
                            Code = "es",
                            Name = "Spanish"
                        },
                        new
                        {
                            Code = "ar",
                            Name = "Arabic"
                        },
                        new
                        {
                            Code = "fr",
                            Name = "French"
                        },
                        new
                        {
                            Code = "bn",
                            Name = "Bengali"
                        },
                        new
                        {
                            Code = "pt",
                            Name = "Portuguese"
                        },
                        new
                        {
                            Code = "ur",
                            Name = "Urdu"
                        },
                        new
                        {
                            Code = "id",
                            Name = "Indonesian"
                        },
                        new
                        {
                            Code = "zh-TW",
                            Name = "Standard Chinese (Traditional)"
                        },
                        new
                        {
                            Code = "ru",
                            Name = "Russian"
                        },
                        new
                        {
                            Code = "ja",
                            Name = "Japanese"
                        },
                        new
                        {
                            Code = "pa",
                            Name = "Punjabi"
                        },
                        new
                        {
                            Code = "de",
                            Name = "German"
                        },
                        new
                        {
                            Code = "jv",
                            Name = "Javanese"
                        },
                        new
                        {
                            Code = "ko",
                            Name = "Korean"
                        },
                        new
                        {
                            Code = "te",
                            Name = "Telugu"
                        },
                        new
                        {
                            Code = "vi",
                            Name = "Vietnamese"
                        },
                        new
                        {
                            Code = "mr",
                            Name = "Marathi"
                        },
                        new
                        {
                            Code = "tr",
                            Name = "Turkish"
                        },
                        new
                        {
                            Code = "ta",
                            Name = "Tamil"
                        },
                        new
                        {
                            Code = "it",
                            Name = "Italian"
                        },
                        new
                        {
                            Code = "yue",
                            Name = "Yue Chinese (Cantonese)"
                        },
                        new
                        {
                            Code = "th",
                            Name = "Thai"
                        },
                        new
                        {
                            Code = "gu",
                            Name = "Gujarati"
                        },
                        new
                        {
                            Code = "kn",
                            Name = "Kannada"
                        },
                        new
                        {
                            Code = "fa",
                            Name = "Persian (Farsi)"
                        },
                        new
                        {
                            Code = "pl",
                            Name = "Polish"
                        },
                        new
                        {
                            Code = "uk",
                            Name = "Ukrainian"
                        },
                        new
                        {
                            Code = "ml",
                            Name = "Malayalam"
                        },
                        new
                        {
                            Code = "ms",
                            Name = "Malay"
                        },
                        new
                        {
                            Code = "ha",
                            Name = "Hausa"
                        },
                        new
                        {
                            Code = "my",
                            Name = "Burmese"
                        },
                        new
                        {
                            Code = "su",
                            Name = "Sundanese"
                        },
                        new
                        {
                            Code = "bho",
                            Name = "Bhojpuri"
                        },
                        new
                        {
                            Code = "nl",
                            Name = "Dutch"
                        },
                        new
                        {
                            Code = "yo",
                            Name = "Yoruba"
                        },
                        new
                        {
                            Code = "or",
                            Name = "Odia (Oriya)"
                        },
                        new
                        {
                            Code = "sd",
                            Name = "Sindhi"
                        },
                        new
                        {
                            Code = "am",
                            Name = "Amharic"
                        },
                        new
                        {
                            Code = "mai",
                            Name = "Maithili"
                        },
                        new
                        {
                            Code = "uz",
                            Name = "Uzbek"
                        },
                        new
                        {
                            Code = "skr",
                            Name = "Saraiki"
                        },
                        new
                        {
                            Code = "ne",
                            Name = "Nepali"
                        },
                        new
                        {
                            Code = "si",
                            Name = "Sinhala"
                        },
                        new
                        {
                            Code = "km",
                            Name = "Khmer"
                        },
                        new
                        {
                            Code = "az",
                            Name = "Azerbaijani"
                        },
                        new
                        {
                            Code = "ro",
                            Name = "Romanian"
                        },
                        new
                        {
                            Code = "ceb",
                            Name = "Cebuano"
                        });
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("AllowedOrigins")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLeadCollectionEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWebsiteChatbotEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWhatsAppEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("KnowledgeBaseText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadCollectionInstruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxTokensPerSession")
                        .HasColumnType("integer");

                    b.Property<int>("MonthlyTokenLimit")
                        .HasColumnType("integer");

                    b.Property<int>("MonthlyTokenUsage")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemInstruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TokenUsageMonthStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WelcomeMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.WhatsAppAutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReplyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggerKeyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WhatsAppAutomationRules");
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.WhatsAppConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerifyToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WabaId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WhatsAppConfigs");
                });

            modelBuilder.Entity("LanguageTenant", b =>
                {
                    b.Property<string>("SupportedLanguagesCode")
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantsId")
                        .HasColumnType("uuid");

                    b.HasKey("SupportedLanguagesCode", "TenantsId");

                    b.HasIndex("TenantsId");

                    b.ToTable("LanguageTenant");
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("HattieAI.Domain.Entities.ChatSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.KnowledgeChunk", b =>
                {
                    b.HasOne("HattieAI.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId1");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LanguageTenant", b =>
                {
                    b.HasOne("HattieAI.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("SupportedLanguagesCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattieAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
