// <auto-generated />
using System;
using HattieAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HattieAI.Infrastructure.Migrations
{
    [DbContext(typeof(HattieDbContext))]
    partial class HattieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HattieAI.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Code");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Code = "zh-CN",
                            Name = "Mandarin Chinese"
                        },
                        new
                        {
                            Code = "hi",
                            Name = "Hindi"
                        },
                        new
                        {
                            Code = "es",
                            Name = "Spanish"
                        },
                        new
                        {
                            Code = "ar",
                            Name = "Arabic"
                        },
                        new
                        {
                            Code = "fr",
                            Name = "French"
                        },
                        new
                        {
                            Code = "bn",
                            Name = "Bengali"
                        },
                        new
                        {
                            Code = "pt",
                            Name = "Portuguese"
                        },
                        new
                        {
                            Code = "ur",
                            Name = "Urdu"
                        },
                        new
                        {
                            Code = "id",
                            Name = "Indonesian"
                        },
                        new
                        {
                            Code = "zh-TW",
                            Name = "Standard Chinese (Traditional)"
                        },
                        new
                        {
                            Code = "ru",
                            Name = "Russian"
                        },
                        new
                        {
                            Code = "ja",
                            Name = "Japanese"
                        },
                        new
                        {
                            Code = "pa",
                            Name = "Punjabi"
                        },
                        new
                        {
                            Code = "de",
                            Name = "German"
                        },
                        new
                        {
                            Code = "jv",
                            Name = "Javanese"
                        },
                        new
                        {
                            Code = "ko",
                            Name = "Korean"
                        },
                        new
                        {
                            Code = "te",
                            Name = "Telugu"
                        },
                        new
                        {
                            Code = "vi",
                            Name = "Vietnamese"
                        },
                        new
                        {
                            Code = "mr",
                            Name = "Marathi"
                        },
                        new
                        {
                            Code = "tr",
                            Name = "Turkish"
                        },
                        new
                        {
                            Code = "ta",
                            Name = "Tamil"
                        },
                        new
                        {
                            Code = "it",
                            Name = "Italian"
                        },
                        new
                        {
                            Code = "yue",
                            Name = "Yue Chinese (Cantonese)"
                        },
                        new
                        {
                            Code = "th",
                            Name = "Thai"
                        },
                        new
                        {
                            Code = "gu",
                            Name = "Gujarati"
                        },
                        new
                        {
                            Code = "kn",
                            Name = "Kannada"
                        },
                        new
                        {
                            Code = "fa",
                            Name = "Persian (Farsi)"
                        },
                        new
                        {
                            Code = "pl",
                            Name = "Polish"
                        },
                        new
                        {
                            Code = "uk",
                            Name = "Ukrainian"
                        },
                        new
                        {
                            Code = "ml",
                            Name = "Malayalam"
                        },
                        new
                        {
                            Code = "ms",
                            Name = "Malay"
                        },
                        new
                        {
                            Code = "ha",
                            Name = "Hausa"
                        },
                        new
                        {
                            Code = "my",
                            Name = "Burmese"
                        },
                        new
                        {
                            Code = "su",
                            Name = "Sundanese"
                        },
                        new
                        {
                            Code = "bho",
                            Name = "Bhojpuri"
                        },
                        new
                        {
                            Code = "nl",
                            Name = "Dutch"
                        },
                        new
                        {
                            Code = "yo",
                            Name = "Yoruba"
                        },
                        new
                        {
                            Code = "or",
                            Name = "Odia (Oriya)"
                        },
                        new
                        {
                            Code = "sd",
                            Name = "Sindhi"
                        },
                        new
                        {
                            Code = "am",
                            Name = "Amharic"
                        },
                        new
                        {
                            Code = "mai",
                            Name = "Maithili"
                        },
                        new
                        {
                            Code = "uz",
                            Name = "Uzbek"
                        },
                        new
                        {
                            Code = "skr",
                            Name = "Saraiki"
                        },
                        new
                        {
                            Code = "ne",
                            Name = "Nepali"
                        },
                        new
                        {
                            Code = "si",
                            Name = "Sinhala"
                        },
                        new
                        {
                            Code = "km",
                            Name = "Khmer"
                        },
                        new
                        {
                            Code = "az",
                            Name = "Azerbaijani"
                        },
                        new
                        {
                            Code = "ro",
                            Name = "Romanian"
                        },
                        new
                        {
                            Code = "ceb",
                            Name = "Cebuano"
                        });
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KnowledgeBaseText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemInstruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("LanguageTenant", b =>
                {
                    b.Property<string>("SupportedLanguagesCode")
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantsId")
                        .HasColumnType("uuid");

                    b.HasKey("SupportedLanguagesCode", "TenantsId");

                    b.HasIndex("TenantsId");

                    b.ToTable("LanguageTenant");
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("HattieAI.Domain.Entities.ChatSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LanguageTenant", b =>
                {
                    b.HasOne("HattieAI.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("SupportedLanguagesCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HattieAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HattieAI.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
